version: '3.5'
services:
  back:
    depends_on:
      - bd_mysql
    build:
      context: ./anc-pensar-back
      dockerfile: Dockerfile
    container_name: app-back
    restart: unless-stopped
    #command: npm run build && npm run start #node dist/main
    ports:
      - "3000:3000"
    
    env_file:
      - ./anc-pensar-back/.env
    #environment:
    #  TYPEORM_DATABASE: ancasti
    #  TYPEORM_USERNAME: root
    #  TYPEORM_PASSWORD: ANC.2020
    networks:
      - app-network

  bd_mysql:
    restart: unless-stopped
    image: mysql:5.7
    command:
      --disable-partition-engine-check
      --innodb_use_native_aio=0
      --max_allowed_packet=128M
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    container_name: bd_mysql
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: ANC.2020
      MYSQL_DATABASE: ancasti
      MYSQL_USER: root
      MYSQL_PASSWORD: ANC.2020
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  front:
    build:
      context: ./anc-pensar-front
      dockerfile: Dockerfile
    container_name: app-front2  
    restart: unless-stopped
    ports:
      -  80:80
    env_file:
      - ./anc-pensar-front/.env
    networks:
      - app-network
  

      
 # afip_api:
 #   build:
  #    context: ./afip-rest
 #     dockerfile: Dockerfile
 #   container_name: afip-api
 #   restart: unless-stopped
 #   #ports:
    #  - "3000:3000"    
  #  networks:
 #     - app-network 

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
 # node_modules:


  
   # environment:
   #   TYPEORM_HOST: bd
   #   TYPEORM_USERNAME: ancasti_user
   #  TYPEORM_PASSWORD: Capresca.2019
   #  TYPEORM_DATABASE: ancasti
   #  TYPEORM_PORT: 3306
#ALTER USER 'root'@'localhost' IDENTIFIED BY 'Capresca.2019';
#GRANT ALL PRIVILEGES ON *.* TO 'ancasti_user'@'localhost' IDENTIFIED BY 'Capresca.2019';
#CREATE DATABASE ancasti;
#DROP DATABASE ancasti;

  ##CONEXION AL BACK
   # environment:
   #   - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
   #   - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
   # volumes:
   #    - ./app-ui:/usr/src/app/app-ui
   #    - /usr/src/app/app-ui/node_modules

  #front:
   # build: ./anc-pensar-front
   # command: ng serve --host 0.0.0.0 --poll=500
   # ports:
   #   - 80:8080
    #expose:
   #   - 80
    #user: ${CURRENT_UID}
    #volumes:
    #  - ./angular-project:/usr/app/angular-project