version: '2'
services:

  back:
    image: ancasti-back
    ports:
      - "3000:3000"
    env_file:
      - back.env
      
  bd:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: asdqw12g34g34gg12
      MYSQL_DATABASE: ancasti
      MYSQL_USER: root
      MYSQL_PASSWORD: asdqw12g34g34gg12